# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GH Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download...
      uses: actions/checkout@v2
    - name: Install...
      run: yarn install --frozen-lockfile
    - name: Build...
      run: yarn build
    - name: Deploy...
      uses: crazy-max/ghaction-github-pages@v2.2.0
